- name: Create config dir
  file:
      path: /root/psql-data
      state: directory
- name: Run postgresql docker
  docker_container:
      name: "psql-database"
      image: postgres
      state: started
      restart: yes
      restart_policy: "unless-stopped"
      volumes:
        - /root/psql-data:/var/lib/postgresql/data
      published_ports:
         "{{ docker_host }}:5432:5432"
      env:
          POSTGRES_PASSWORD: "{{ postgresql_password }}"
- name: Postgresql config
  template:
      src: pg_hba.j2
      dest: /root/psql-data/pg_hba.conf
- name: Install python lib
  apt:
      pkg:
          - python-psycopg2
      state: present
      update_cache: true
