- name: Create config dir
  file:
      path: "{{postgresql_data_path}}"
      state: directory
- name: Run postgresql docker
  docker_container:
      name: "psql-database"
      image: "postgres:11"
      state: started
      restart: yes
      restart_policy: "{{ docker_restart_policy }}"
      pull: "{{ docker_pull }}"
      volumes:
        - "{{ postgresql_data_path }}:/var/lib/postgresql/data"
      published_ports:
         "{{ docker_host }}:{{ postgresql_port }}:5432"
      env:
          POSTGRES_PASSWORD: "{{lookup('password', '{{ passwords_dir }}postgresql_password')}}"
- name: Postgresql config
  template:
      src: pg_hba.j2
      dest: /root/psql-data/pg_hba.conf
- name: Install python lib
  apt:
      pkg:
          - python-psycopg2
          - python3-psycopg2
      state: present
      update_cache: true
- name: Install postgresql client tools
  apt:
      pkg:
          - postgresql-client
      state: present
      update_cache: true
- name: Wait for postgresql to be up
  shell: "/usr/bin/pg_isready -h {{ docker_host }} -p {{ postgresql_port }}"
  register: result
  retries: 50
  delay: 3
  until: result.rc == 0
- name: Set postgresql password for good
  shell: "docker exec -u postgres psql-database psql -c \"ALTER USER postgres PASSWORD '{{lookup('password', '{{ passwords_dir }}postgresql_password')}}';\""
