- name: Install nginx
  apt: pkg=nginx state=present update_cache=true
- name: Remove default
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify:
    - restart nginx
- name: Copy config template
  template:
      src: sites/default
      dest: /etc/nginx/sites-available
- name: Symlink config
  file:
      src: /etc/nginx/sites-available/default
      dest: /etc/nginx/sites-enabled/default
      state: link
  notify:
      - restart nginx
- name: Copy ssl cert
  copy:
      src: "{{ local_cert_path }}"
      dest: "{{ nginx_cert }}"
- name: Copy ssl key
  copy:
      src: "{{ local_cert_key_path }}"
      dest: "{{ nginx_cert_key }}"
