- name: Create nginx config path
  file:
      path: "{{ nginx_sites_vol_path }}"
      state: directory
- name: Place config
  template:
      src: nginx.conf
      dest: /root/nginx.conf
- name: Copy default site template
  template:
      src: sites/default
      dest: "{{ nginx_sites_vol_path}}"
- name: Copy matrix site template
  template:
      src: sites/matrix
      dest: "{{ nginx_sites_vol_path}}"
- name: Copy riot site template
  template:
      src: sites/riot
      dest: "{{ nginx_sites_vol_path}}"
- name: Copy gitea site template
  template:
      src: sites/gitea
      dest: "{{ nginx_sites_vol_path}}"
- name: Start nginx docker
  docker_container:
      name: "nginx-docker"
      image: "nginx"
      state: started
      restart: yes
      restart_policy: "unless-stopped"
      volumes:
          - "{{ nginx_sites_vol_path }}:/etc/nginx/sites-enabled:ro"
          - "{{ cert_key_path }}:{{ nginx_cert_key }}:ro"
          - "{{ cert_path }}:{{ nginx_cert }}:ro"
          - "/root/nginx.conf:/etc/nginx/nginx.conf:ro"
          - "{{ nginx_http_root }}:/usr/share/nginx/html:ro"
      published_ports:
          - "{{ nginx_https_port }}:443"
          - "{{ nginx_http_port }}:80"
          - "{{ matrix_federation_port }}:{{ matrix_federation_port }}"
