- hosts: fricloudtest
  vars_files:
    - defaults.yml
  roles:
      - role: nftables
        become: yes
        tags: nft
      - role: certs
        become: yes
        tags: certs
      - role: ldap
        become: yes
        tags: ldap
      - role: docker
        become: yes
        tags: docker
      - role: website
        become: yes
        tags: website
      - role: nginx
        become: yes
        tags: nginx
      - role: postgresql
        become: yes
        tags: database
      - role: gitea
        become: yes
        tags: gitea
      - role: prometheus
        become: yes
        tags: prometheus
      - role: nextcloud-simple-apps
        become: yes
        tags: nextcloud-simple-apps
      - role: nextcloud
        become: yes
        tags: nextcloud
      - role: email
        become: yes
        tags: email
      - role: matrix
        become: yes
        tags: matrix
      - role: restore
        become: yes
        tags:
          - never
          - restore
