---
- hosts: testvm
  vars_files:
    defaults.yml
  roles:
      - role: ldap
        become: yes
        vars:
        tags: ldap
      - role: docker
        become: yes
        tags: docker
      - role: nginx
        become: yes
        tags: nginx
      - role: postgresql
        become: yes
        tags: database
      - role: gitea
        become: yes
        tags: gitea
      - role: prometheus
        become: yes
        tags: prometheus
      - role: nextcloud
        become: yes
        tags: nextcloud
