---
- hosts: testvm
  vars:
      postgresql_password: TODOthisIsTerribleWeNeedAnAlternativeTODO
      docker_host: 172.17.0.1
  roles:
      - role: ldap
        become: yes
        vars:
            dc_domain: fricloud
            dc_domain_top: dk
            slapd_pass: test123
            domain_admin_pass: test123
        tags: ldap
      - role: nginx
        become: yes
        tags: nginx
      - role: docker
        become: yes
        tags: docker
      - role: postgresql
        become: yes
        tags: database
      - role: gitea
        become: yes
        vars:
            gitea_db_pass: "hejmeddig"
            gitea_ssh_domain: "git.fricloud.dk"
            gitea_ssh_port: "222"
            gitea_http_url: "http://192.168.122.5:8000"
            gitea_data_path: "/root/gitea-data"
        tags: gitea
