---
- hosts: testvm
  vars:
    docker_host: 172.17.0.1
  roles:
      - role: ldap
        become: yes
        vars:
            dc_domain: fricloud
            dc_domain_top: dk
            slapd_pass: test123
            domain_admin_pass: test123
        tags: ldap
      - role: nginx
        become: yes
        tags: nginx
      - role: docker
        become: yes
        tags: docker
      - role: postgresql
        become: yes
        vars:
            postgresql_password: TODOthisIsTerribleWeNeedAnAlternativeTODO
        tags: database
      - role: prometheus
        become: yes
        tags: docker
