---
- hosts: fricloudtest
  vars_files:
    defaults.yml
  roles:
      - role: certs
        become: yes
        tags: certs
      - role: ldap
        become: yes
        tags: ldap
      - role: docker
        become: yes
        tags: docker
      - role: nginx
        become: yes
        tags: nginx
      - role: postgresql
        become: yes
        tags: database
      - role: gitea
        become: yes
        tags: gitea
      - role: prometheus
        become: yes
        tags: prometheus
      - role: nextcloud
        become: yes
        tags: nextcloud
      - role: matrix
        become: yes
        tags: matrix
