- name: Create db user
  postgresql_user:
      name: gitea
      password: "{{ gitea_db_pass }}"
      login_host: localhost
      login_password: "{{ postgresql_password }}"
- name: Create db
  postgresql_db:
      name: gitea_db
      encoding: UTF-8
      owner: gitea
      login_host: localhost
      login_password: "{{ postgresql_password }}"
- name: Run gitea docker
  docker_container:
      name: "gitea-docker"
      image: gitea/gitea:latest
      state: started
      published_ports:
          - "3000:3000"
          - "222:22"
      env:
          USER_UID: "1000"
          USER_GID: "1000"
          DB_TYPE: "postgres"
          DB_HOST: "172:5432"
          DB_NAME: "gitea_db"
          DB_USER: "gitea"
          DB_PASSWD: "{{ gitea_db_pass }}"
