- name: Copy website git
  copy:
    src: "files/frontpage"
    dest: "/tmp/"
- name: Create build directory
  file: path=/tmp/frontpage state=directory
- name: Build docker image
  docker_image:
    build:
      path: "/tmp/frontpage"
      pull: yes
    name: "website"
    source: build
- name: Create folder for registered emails
  file:
    path: "{{ emails_location }}"
    state: touch
    owner: "65534"
    group: "65534"
    mode: "600"
- name: Run website container
  docker_container:
    name: "website"
    image: "website"
    state: started
    restart: yes
    restart_policy: "{{ docker_restart_policy }}"
    volumes:
      - "{{ emails_location }}:/var/emails"
    published_ports:
      - "{{ docker_host}}:{{ website_port }}:80"
    env:
        GIT_REVISION: "{{ git_revision }}"
