- name: Install dependencies
  apt:
    pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
    state: present
    update_cache: true

- name: Add Docker PGP key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: Add docker APT repo
  apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ansible_distribution_release}} stable

- name: Install docker
  apt:
      pkg: docker-ce
      state: present
      update_cache: true

- name: Install python pip
  apt:
      pkg: python-pip
      state: present
      update_cache: true

- name: Install docker lib for python
  command: pip install docker

- name: Add daemon config
  template:
    src: daemon.json
    dest: /etc/docker/daemon.json

- name: Restart docker service
  systemd:
    name: docker
    enabled: yes
    state: restarted
