- name: Install dependencies
  apt:
    pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
    state: present
    update_cache: true

- name: Install docker and python wrappers
  apt:
    pkg:
        - docker.io
        - python-docker
        - python3-docker
    state: present
    update_cache: true

- name: Add daemon config
  template:
    src: daemon.json
    dest: /etc/docker/daemon.json

- name: Restart docker service
  systemd:
    name: docker
    enabled: yes
    state: restarted
