- name: Install dependencies
  apt:
    pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
    state: present
    update_cache: true

- name: Install docker and python wrappers
  apt:
    pkg:
        - docker.io
        - python-docker
        - python3-docker
    state: present
    update_cache: true

- name: Add daemon config
  template:
    src: daemon.json
    dest: /etc/docker/daemon.json

- name: Ensure docker dir
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory

- name: Ensure docker uses iptables
  template:
    src: "iptables-disabled.conf"
    dest: /etc/systemd/system/docker.service.d/iptables-disabled.conf
- name: Restart docker service
  systemd:
    state: restarted
    daemon-reload: yes
    name: docker
