- name: write existing apps to variable
  shell: "docker exec --user www-data nextcloud php occ app:list"
  register: installedApps
  ignore_errors: yes

- name: Install nextcloud apps
  shell: "docker exec --user www-data nextcloud php occ app:install {{ item }}"
  when: 'item not in installedApps.stdout'
  loop:
    - calendar
    - text
    - tasks
    - drawio
    - twofactor_u2f
    - twofactor_totp
