{
 "title": "Main dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Used memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "node_memory_Active_bytes" }
   ]
  },
  {
   "title": "Remaining disk space on /",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint='/'}"
    }
   ]
  },
  {
   "title": "I/O network per minute (bytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total[1m])+rate(node_network_transmit_bytes_total[1m])"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{mode!='idle'}[1m])"
    }
   ]
  }
 ]
}