{
 "title": "Main dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Running containers percent",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100*((engine_daemon_container_states_containers{state='running'})/engine_daemon_container_states_containers)"
    }
   ]
  },
  {
   "title": "Remaining disk space on /",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail{mountpoint='/'}"
    }
   ]
  },
  {
   "title": "Used memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal-node_memory_MemAvailable"
    }
   ]
  },
  {
   "title": "CPU Time per minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(node_cpu{mode!='idle'}[1m])"
    }
   ]
  },
  {
   "title": "I/O network per minute (bytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes{device='ens3'}[1m])+rate(node_network_transmit_bytes{device='ens3'}[1m])"
    }
   ]
  }
 ]
}