scrape_configs:
  - job_name: prometheus

    scrape_interval: 5s
    static_configs:
     - targets: ['localhost:{{prometheus_port}}']
  - job_name: Host
    scrape_interval: 5s
    static_configs:
      - targets: ['{{ docker_host }}:{{node_export_port}}']
  - job_name: Docker
    scrape_interval: 5s
    static_configs:
      - targets: ['{{ docker_host }}:9323']
