scrape_configs:
  - job_name: prometheus

    scrape_interval: 5s
    static_configs:
     - targets: ['localhost:9090']
  - job_name: Host
    scrape_interval: 5s
    static_configs:
      - targets: ['{{ docker_host }}:9100']
  - job_name: Docker
    scrape_interval: 5s
    static_configs:
      - targets: ['{{ docker_host }}:9323']
