scrape_configs:
  - job_name: prometheus

    scrape_interval: 5s
    static_configs:
     - targets: ['localhost:{{prometheus_port}}']
  - job_name: Host
    scrape_interval: 5s
    static_configs:
      - targets: ['{{ docker_host }}:{{node_export_port}}']
  - job_name: Docker
    scrape_interval: 5s
    static_configs:
      - targets: ['{{ docker_host }}:9323']
  - job_name: Synapse
    scrape_interval: 5s
    static_configs:
      - targets: ['{{ docker_host }}:{{ matrix_metrics_port }}']
  - job_name: Grafana
    scrape_interval: 5s
    static_configs:
      - targets: ['{{ docker_host }}:{{ grafana_port}}']
    basic_auth:
      username: grafana
      password: {{ lookup('password', '{{ passwords_dir }}grafana_metrics_pass') }}
  - job_name: gitea
    scrape_interval: 5s
    static_configs:
      - targets: ['{{ docker_host }}:{{ gitea_http_port }}']
    bearer_token: {{ lookup('password', '{{ passwords_dir }}gitea_metrics_key chars=ascii_letters,digits length=60') }}
